---
  vpcs:
    - vpcname: vpc-0189dd71d9ff0b91b
      configurations:
        - vpccidr: 10.0.0.0/16
          vpcregion: ap-south-1
          IGW: yes
    - vpcname: vpc-05715f6e510e2fc54
      configurations:
        - vpccidr: 10.1.0.0/16
          vpcregion: ap-south-1
          IGW: yes
  
  subnetsapsouth1a:
    - subnetname: subnet-0e97183facf2d81e0
      configs:
        - subcidr: 10.0.5.0/24
          subaz: ap-south-1a
          subreg: ap-south-1
          subvpcid: vpc-0189dd71d9ff0b91b
          subtags: publicsubnet-vpc1
          sumap_public: yes
    - subnetname: subnet-0f4d069d6cb4cfb9f
      configs:
        - subcidr: 10.0.6.0/24
          subaz: ap-south-1a
          subreg: ap-south-1
          subvpcid: vpc-0189dd71d9ff0b91b
          subtags: privatesubnet-vpc1
          sumap_public: no
    - subnetname: subnet-0c4bc2ad9da77b24c
      configs:
        - subcidr: 10.0.7.0/24
          subaz: ap-south-1a
          subreg: ap-south-1
          subvpcid: vpc-0189dd71d9ff0b91b
          subtags: privatesubnet-vpc1
          sumap_public: no
    - subnetname: subnet-0f0d71068b9316212
      configs:
        - subcidr: 10.1.8.0/24
          subaz: ap-south-1a
          subreg: ap-south-1
          subvpcid: vpc-05715f6e510e2fc54
          subtags: privatesubnet-vpc2
          sumap_public: no
    - subnetname: subnet-0435b28be96df93c0
      configs:
        - subcidr: 10.1.9.0/24
          subaz: ap-south-1a
          subreg: ap-south-1
          subvpcid: vpc-05715f6e510e2fc54
          subtags: publicsubnet-vpc2
          sumap_public: no
        
  subnetsapsouth1b:
    - subnetname: subnet-081c8280a148cafb9
      configs:
        - subcidr: 10.0.10.0/24
          subaz: ap-south-1b
          subreg: ap-south-1
          subvpcid: vpc-0189dd71d9ff0b91b
          subtags: publicsubnet-vpc1
          sumap_public: yes

    
  igw_routes:
    - routename: SUB1-PUBL-VPCA-IGW
      confs:
        - igrvpc: vpc-0189dd71d9ff0b91b
          igrregion: ap-south-1
          igrsubnet: subnet-0e97183facf2d81e0
          igrgatewayid: igw-060c18a08b574b8e4
    - routename: SUB5-PUBL-VPCA-IGW
      confs:
        - igrvpc: vpc-0189dd71d9ff0b91b
          igrregion: ap-south-1
          igrsubnet: subnet-081c8280a148cafb9
          igrgatewayid: igw-060c18a08b574b8e4
    - routename: SUB6-PUBL-VPCB-IGW
      confs:
        - igrvpc: vpc-05715f6e510e2fc54
          igrregion: ap-south-1
          igrsubnet: subnet-0435b28be96df93c0
          igrgatewayid: igw-0268dda0a73e1e6c1


  # variables for nat gateway to DB subnet subnet-0c4bc2ad9da77b24c
  natgateways:
    - natgatewayname: nat-0311821a7a8323457
      configure:
        - ngsubnet: subnet-0e97183facf2d81e0
          ngregion: ap-south-1
    - natgatewayname: nat-0c8092977a154c804
      configure:
        - ngsubnet: subnet-0435b28be96df93c0
          ngregion: ap-south-1
    

  # create route record to vpca main route table and associate subnet subnet-0c4bc2ad9da77b24c
  ngw_routes:
    - routename: rtb-0b8a8512b6877eacf
      con:
        - ngrvpc: vpc-0189dd71d9ff0b91b
          ngrvpccidr: 10.0.0.0/16
          ngrregion: ap-south-1
          ngrsubnet: subnet-0c4bc2ad9da77b24c
          ngrgatewayid: nat-0311821a7a8323457
          ngrrouteid: rtb-0b8a8512b6877eacf
    - routename: rtb-02ffc901b18c77929
      con:
        - ngrvpc: vpc-05715f6e510e2fc54
          ngrvpccidr: 10.1.0.0/16
          ngrregion: ap-south-1
          ngrsubnet: subnet-0f0d71068b9316212
          ngrgatewayid: nat-0c8092977a154c804
          ngrrouteid: rtb-02ffc901b18c77929

  # create basic subnets that allow public to access web servers in vpc-a and vpc-b
  create_webserver_sec_groups:
    - secgrpname: sg-0bc96d7e309b81b40
      configurations:
        - secgrpdesc: sec grp for web servers for vpca
          secvpcid: vpc-0189dd71d9ff0b91b
          secregion: ap-south-1
    - secgrpname: sg-04b61c7db5b0bc583
      configurations:
        - secgrpdesc: sec grp for web servers for vpcb
          secvpcid: vpc-05715f6e510e2fc54
          secregion: ap-south-1
  # create keyair for ap-south-1 region
  #createkeypair:
  #  - kpname: apsouth1keypair1
  #    cons:
  #      - kpregion: ap-south-1
  #  - kpname: apsouth1keypair2
  #    cons: 
  #      - kpregion: ap-south-1

  
  # create instance
  crt_inst:
    - instname: i-069b673e96b5759be
      configs:
        - inskeyname: myprimeadmkeypair
          instype: t2.micro
          insimage: ami-0a74bfeb190bd404f
          insregion: ap-south-1
          inssecgrp: sg-0bc96d7e309b81b40
          instags: INSTANCESUBPUB1VPCA-i-069b673e96b5759be
          inspubiptag: 13.234.225.203/32
          inspriiptag: 10.0.5.0/24
          inscount: 1
          insvpcsubnetid: subnet-0e97183facf2d81e0
          insasspubip: yes
    - instname: i-0c1bd2ca9e086a24e
      configs:
        - inskeyname: myprimeadmkeypair
          instype: t2.micro
          insimage: ami-0a74bfeb190bd404f
          insregion: ap-south-1
          inssecgrp: sg-0bc96d7e309b81b40
          instags: INSTANCESUBPUB1VPCA-['i-0c1bd2ca9e086a24e']
          inspubiptag: 13.233.121.75/32
          inspriiptag: 10.0.10.0/24
          inscount: 1
          insvpcsubnetid: subnet-081c8280a148cafb9
          insasspubip: yes
     
  # Create sec groups to app servers in vpca private subnets
  create_appserver_sec_groups:
    - secgrpname: sg-0a5074f7ba955c9a5
      configurations:
        - secgrpdesc: sec grp for app servers for vpca
          secvpcid: vpc-0189dd71d9ff0b91b
          secregion: ap-south-1
          sectarget1: 10.0.5.0/24
          sectarget2: 10.0.10.0/24 
    
  # create instance in appserver of subpri2 in vpca
  crt_inst_app:
    - instname: i-07641a2e4a4b9f71b
      configs:
        - inskeyname: myprimeadmkeypair
          instype: t2.micro
          insimage: ami-0a74bfeb190bd404f
          insregion: ap-south-1
          inssecgrp: sg-0a5074f7ba955c9a5
          instags: INSTANCESUBPRI2VPCA-INST2-SUBPRI2-VPCA
          inspubiptag: INST3SUBPRI2VPCAPUBLICIP
          inspriiptag: 10.0.6.0/24
          inscount: 1
          insvpcsubnetid: subnet-0f4d069d6cb4cfb9f
          insasspubip: no

  # Create sec groups to DB servers in vpca private subnets
  create_dbserver_sec_groups:
    - secgrpname: sg-0e468f5d8f7e95b38
      configurations:
        - secgrpdesc: sec grp for db servers for vpca
          secvpcid: vpc-0189dd71d9ff0b91b
          secregion: ap-south-1
          sectarget1: 10.0.6.0/24
          sectarget2: 10.0.5.0/24
          sectarget3: 10.0.10.0/24


  # create instance
  crt_inst_db:
    - instname: ['i-01dfe6d47865f39eb']
      configs:
        - inskeyname: myprimeadmkeypair
          instype: t2.micro
          insimage: ami-0a74bfeb190bd404f
          insregion: ap-south-1
          inssecgrp: sg-0e468f5d8f7e95b38
          instags: INSTANCESUBPRI3VPCA-['i-01dfe6d47865f39eb']
          inspubiptag: INST4SUBPRI3VPCAPUBLICIP
          inspriiptag: 10.0.7.23/32
          inscount: 1
          insvpcsubnetid: subnet-0c4bc2ad9da77b24c
          insasspubip: no

